### ISSUE TITLE
Assorted v8 improvements

### ISSUE THREAD

**Issue by lg2de** [fluentassertions/fluentassertions#1677]
After release of V6 there are issues reported which cannot be (completely) realized before V7 because of breaking changes.
This issue lists all pending changes including link to related issue(s). It will be updated permanently.

- [ ] Make `ComparableAssertions` more generic - [draft](https://github.com/jnyrup/fluentassertions/tree/GenericIComparableAssertions)
- [x] Remove `GreaterOrEqualTo` (obsolete) methods replaced by `GreaterThanOrEqualTo` (#1673)
- [ ] In `EquivalentValidator` replace the last `IEquivalencyStep` with a hard-coded assertion to replace the `NotImplementedException`. See https://github.com/fluentassertions/fluentassertions/blob/master/Src/FluentAssertions/Equivalency/EquivalencyValidator.cs#L76
- [x] Rename `RespectingRuntimeTypes` to `RespectingRuntimeTypeProperties` or something like that. See #1830. Also, it can be confusing because we also have `IncludingAllRuntimeProperties` and `IncludingAllDeclaredProperties`
- [x] Check whether assertions on `AndWhichConstraint` should be executed within `AssertionScope` after base assertion has failed. See discussion on [Slack](https://fluentassertions.slack.com/archives/C01055CMSD9/p1660070451083999).
- [x] Refactor `AsyncFunctionAssertions` as "real" base class (preparation in #1972).
- [ ] Investigate if we can replace/aid `CallerIdentifier` using `[CallerArgumentExpression]`.
  - sometimes it could also be useful to extract the variable name of the `expected` parameter.
  - this might also let us replace `Expression<>` with `Func<>`
  - investigate whether this works for .NET 4.8 as well
- [ ] Consider renaming `AssertionScope.Current` to `AssertionScope.ThreadInstance` 
- [ ] Consider renaming `FailWith` since it does not always throw
- [x] Consider renaming `ExcludingNestedObjects` to something with _recursive_ in it or _deep_ vs _shallow_
- [ ] Align terminology between "object graph comparison" in the [docs](https://fluentassertions.com/objectgraphs/) vs "structural comparison" in the code.
- [ ] Consider renaming "expected" to "expectation" and "unexpected" to ?, to use nouns instead of adjectives
- [ ] Consider returning `AndWhichConstraint` from `GenericCollectionAssertions.ContainItemsAssignableTo<T>`
- [x] Consider making `EquivalencyValidator` and some other "internal" classes `internal`

**Comment by dennisdoomen** [comment]
Why not use a milestond for this?

**Comment by jnyrup** [comment]
Some thoughts I think we should have in mind:
Just because SemVer allows us breaking everything doesn't mean we have to - or should.

The more exposed an API is, the more havoc breaking it will cause.
E.g. `MemberFactory` could probably be renamed without anyone noticing, but renaming `Be` to `BeEqualTo` would break compilation for ~all consumers of FA.

This discussion has some interesting points on this topic
https://www.youtube.com/watch?v=Os7Rpm3LBkE&t=1s

**Comment by IT-VBFK** [comment]
`Assorted v8 improvements`? 😉

**Comment by dennisdoomen** [comment]
As v8 was released today, I'm going to close this one. We're not planning any breaking changes anytime soon.
