### ISSUE TITLE
More Assertions on types

### ISSUE THREAD

**Issue by jnyrup** [fluentassertions/fluentassertions#645]
We do have an _impressive_ amount of type assertions.
I've tried to lookup the .net type hierarchy and keywords to see what we might be missing.
See the bottom for types and keywords.

Here's a rough sketch of what such APIs could look like, but please notice that I haven't checked if they are:
* even possible
* desirable.

- [ ] ClassAssertions : TypeAssertions<ClassAssertions>
- [ ] ClassSelector : TypeSelector
- [ ] EventInfoAssertions : MemberInfoAssertions<EventInfo, EventInfoAssertions>
- [ ] ~FieldInfoAssertions : MemberInfoAssertions<FieldInfo, FieldInfoAssertions>~
  - [ ] ~[Not]BeVolatile~
  - [ ] ~[Not]BeConst~
- [ ] ~FieldInfoSelector~
  - [ ] ~ThatAre[Not]Volatile~
  - [ ] ~ThatAre[Not]Const~
- [ ] InterfaceAssertions : TypeAssertions<InterfaceAssertions>
- [ ] InterfaceSelector : TypeSelector
- [ ] MemberInfoAssertions
  - [ ] [Not]HaveAccessModifier
  - [ ] ~[Not]BeOverridable~
  - [ ] [Not]BeStatic
  - [ ] [Not]BeAbstract
- [x] MethodInfoSelector
  - [x] ThatAre[Not]Async #1725
  - [ ] ~ThatAre[Not]Overridable~
  - [x] ThatAre[Not]Virtual #1744 
  - [x] ThatAre[Not]Static #1740
  - [x] ThatAre[Not]Abstract #2060
  - [ ] ThatAre[Not]Sealed
- [ ] PropertyInfoSelector
  - [x] NotBeWritable #1256
  - [ ] ~ThatAre[Not]Overridable~
  - [x] ThatAre[Not]Virtual #2054
  - [x] ThatAre[Not]Static #2054
  - [x] ThatAre[Not]Abstract #2054
  - [ ] ThatAre[Not]Sealed
- [ ] ~StructAssertions : TypeAssertions<StructAssertions>~
- [ ] ~StructSelector : TypeSelector~
- [x] TypeAssertions
  - [x] [Not]BeStatic #796
  - [x] [Not]BeAbstract #796
  - [x] [Not]BeSealed #796
- [ ] TypeSelector
  - [ ] ThatAre[Not]Virtual
  - [x] ThatAre[Not]Static #1306
  - [x] ThatAre[Not]Abstract #2058 
  - [x] ThatAre[Not]Sealed #2059 
  - [x] ThatAre[Not]Classes #1306
  - [ ] ThatAre[Not]Structs #2056
  - [ ] ThatAre[Not]Interfaces #2057
- [x] TypeSelectorAssertions
  - [x] [Not]BeSealed #1306

References:

Type hierachy:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/members	

- [ ] Members
  - [ ] Fields
  - [ ] Constants
  - [ ] Properties
  - [ ] Methods
  - [ ] Events
  - [ ] Operators
  - [ ] Indexers
  - [ ] Constructors
  - [ ] Finalizers
- [ ] Classes
- [ ] Structs
- [ ] Interfaces
- [ ] StaticConstructors	

Keywords and which type they apply to:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/

- [ ] member, type
  - [ ] access modifiers:
    - [ ] private
    - [ ] protected
    - [ ] public
    - [ ] internal
    - [ ] protected Internal
- [ ] classes, fields, methods, properties, operators, events, and constructors
  - [ ] static
- [ ] method, property, indexer, or event
  - [ ] virtual
  - [ ] override
- [ ] member
  - [ ] new
- [ ] type
  - [ ] abstract
  - [ ] unsafe
- [ ] method
  - [ ] extern
  - [ ] async
- [ ] class
  - [ ] sealed
- [ ] class, struct, interface, method
  - [ ] partial
- [ ] field
  - [ ] volatile
  - [ ] readonly
  - [ ] const

**Comment by dennisdoomen** [comment]
Is this something you need yourself? If not, I really need some help to finish https://github.com/fluentassertions/fluentassertions/milestone/10

**Comment by jnyrup** [comment]
I have a case that could be more readable with `ThatAreAbstract`.
Aside from that one, I currently don't any of these methods myself.
Let's discuss on Slack how I be of better help.

**Comment by melchiork** [comment]
Checking `partial` keyword seems all but impossible. After the compilation all the code is merged into single type and there is no information whatsoever that the class was assembled from multiple parts. One less to worry about.

**Comment by obiwanjacobi** [comment]
In that same light, you could also think of something like:

```csharp
            noClasses()
                    .that()
                    .resideIn("..model..")
                    .should()
                    .dependOnClassesThat()
                    .resideIn("..application..");
```

Not sure how you would phrase that, but the idea here is to make assertions on the design of the code. 
Could be a real help to validate architectural rules (Test-Driven-Architecture? ;-)

**Comment by Evangelink** [comment]
@jnyrup Hey sorry to bother! I am genuinely interested in knowing in which situation you are using tests which ensure a modifier or a keyword. As for now, I have always written tests targeting the "feature" provided by the method but not the "how".

**Comment by jnyrup** [comment]
@Evangelink No need to apologize.
There are some examples in the [docs](https://fluentassertions.com/typesandmethods/).

At work I've used the type assertion API, as a poor man's code analyzer, to avoid some coding pitfalls.
E.g. using the wrong overload of [`RangeValidatorAttribute`](https://docs.microsoft.com/en-us/previous-versions/msp-n-p/ee779494(v=pandp.10)).

For example a `double` member in our API was annotated with
```
[RangeValidator(0, RangeBoundaryType.Inclusive, 100, RangeBoundaryType.Inclusive)]
```
but should have been 
```
[RangeValidator(0.0, RangeBoundaryType.Inclusive, 100.0, RangeBoundaryType.Inclusive)]
```

IIRC the `int` overload downcasts the `double` to an `int`, so a value of `100.7` was accepted, but should have been rejected.

Then I wrote a ~unit~ test, that scans our API using the type assertion API to detect such cases.

**Comment by Evangelink** [comment]
Oh, I see! I had a few cases like that in the past but I went for the analyzer option :)
Anyway good to know about this.

Thank you @jnyrup

**Comment by rubenrorije** [comment]
I think this is extremely useful. I am doing similar things to the RangeValidator test above in my projects to enforce certain project specific implementation policies without having to create code analyzers (which I did not study yet).
My specific usecase in this case was to make sure that certain interfaces were implemented explicitly and it would be useful to have this out-of-the-box. 
Some additions I did create in my own project:

- ClassSelector
  - ThatAreValueTypes
  - ThatArePublicOrInternal
- ClassAssertions
  - ImplementsExplicit<TInterface>

**Comment by chvollm** [comment]
@jnyrup  Is there an ordered list of top 10 requests?

**Comment by jnyrup** [comment]
> @jnyrup  Is there an ordered list of top 10 requests?

For the APIs from this issue?
No. 
I would probably go with what brings most consistency across all type assertions classes.

**Comment by 94sedighi** [comment]
hi @jnyrup 
I am working on PropertyInfo and PropertyInfoSelector (ThatAreOverridable and ThatAreNotOverridable) and i have finished the implementation and tests. But some ApproveApi Tests fails, because of difference in ...verified.txt and ...recieved.txt. Are we supposed to enter the changes manually to the ...verified.txt files?

**Comment by jnyrup** [comment]
You can run one of the `AcceptApiChanges` scripts from the root folder.

**Comment by 94sedighi** [comment]
@jnyrup 
In PropertyInfoSelector you wanted also to have ThatAre[Not]Sealed, but it is difficult to find out if a property is marked as sealed, MethodInfo Class don't offer a property or a method to check it.
but the purpose of checking a property for sealed is to make sure that it is not overridable, and this feature i have already implemented this feature, so you can remove it from checklist.

And as i understand PropertyInfoSelector.cs is only a filter, so we can implement the functionalities there and test them in PropertyInfoSelectorSpecs.cs am i right?

If yes, then i will do a pull request for PropertyInfoSelector funtionalities.

**Comment by jnyrup** [comment]
Thanks for all the implementations contributed over the years ❤️ 
I'm closing this issue for now since the vast majority of the APIs I brainstormed back then have now been implemented and remaining ones are getting more and more esoteric to see in a unit test.

For the remainder of the APIs, if you would find it useful in your usage of Fluent Assertions, please open a new issue describing the use-case, then we can discuss the it there.
